import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import {
  DOCKER_HUB_FULL_DESCRIPTION_MAX,
  parseEnvExample,
  readSourceRepoUrl,
  renderDockerHubOverview,
} from '../../../src/publishers/render-docker-hub-overview.js';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');

// A faithful slice of what the generator emits: free prose, then annotations,
// then the variable. The annotations come LAST, which is the whole trap.
const ENV_EXAMPLE = `# .env.example — Test MCP Server
# Auto-generated by @suite/generator. Do not edit.

# User key — a long-lived key, exchanged for a session token
# description: Long-lived user key, exchanged automatically for a session token.
# isSecret: true
# isRequired: true
MCP_AUTH_USER_KEY=

# description: Upstream API root. The server will not start without it.
# isSecret: false
# isRequired: true
MCP_API_BASE_URL=

# description: HTTP port in hosted mode; ignored in stdio mode
# isSecret: false
# isRequired: false
PORT=8080
`;

describe('parseEnvExample', () => {
  it('reads the annotated description, not the last comment line', () => {
    const entries = parseEnvExample(ENV_EXAMPLE);
    const userKey = entries.find((e) => e.name === 'MCP_AUTH_USER_KEY')!;
    expect(userKey.description).toBe(
      'Long-lived user key, exchanged automatically for a session token.',
    );
    // The regression this exists for: `file-marketplace-issue.ts` keeps only the
    // last comment line, so every variable's "description" on the Cline and
    // mcp.so submissions reads `isRequired: true`.
    expect(userKey.description).not.toContain('isRequired');
    expect(userKey.description).not.toContain('isSecret');
  });

  it('carries the secret and required flags', () => {
    const entries = parseEnvExample(ENV_EXAMPLE);
    expect(entries.find((e) => e.name === 'MCP_AUTH_USER_KEY')).toMatchObject({
      isSecret: true,
      isRequired: true,
    });
    expect(entries.find((e) => e.name === 'MCP_API_BASE_URL')).toMatchObject({
      isSecret: false,
      isRequired: true,
    });
    expect(entries.find((e) => e.name === 'PORT')).toMatchObject({ isRequired: false });
  });

  it('does not lose a description to the blank line the generator writes', () => {
    // The generator separates blocks with blank lines. A parser that clears its
    // buffer on any non-comment line drops the description of every variable.
    const entries = parseEnvExample('# description: Kept.\n\nFOO=\n');
    expect(entries[0]?.description).toBe('Kept.');
  });
});

async function writeProduct(dir: string, env: string): Promise<void> {
  await fs.mkdir(path.join(dir, 'assets'), { recursive: true });
  await fs.writeFile(path.join(dir, '.env.example'), env);
  await fs.writeFile(
    path.join(dir, 'server.json'),
    JSON.stringify({ description: 'Test MCP server for certified evidence.' }),
  );
}

async function render(env: string): Promise<{ full: string; short: string }> {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'dh-overview-'));
  try {
    await writeProduct(dir, env);
    return await renderDockerHubOverview({
      mcpName: 'test-mcp',
      packageDir: dir,
      repoRoot,
      version: '2.0.0',
      dockerImageName: 'gdigital/test',
      npmPackageName: '@g-digital/mcp-test',
      repoUrl: 'https://github.com/g-digital-by-Garrigues/Test_MCP',
      license: 'MIT',
      releaseTag: 'v2.0.0',
    });
  } finally {
    await fs.rm(dir, { recursive: true, force: true });
  }
}

describe('renderDockerHubOverview', () => {
  it('fits inside Docker Hub’s cap, with room to grow', async () => {
    const { full } = await render(ENV_EXAMPLE);
    expect(full.length).toBeLessThan(DOCKER_HUB_FULL_DESCRIPTION_MAX);
    // The README did not merely exceed the cap — it was 42,521 bytes by v2.0.0
    // and climbing. A rendered overview that only just fits would be the same
    // bug deferred, so hold it to a fraction of the budget.
    expect(full.length).toBeLessThan(DOCKER_HUB_FULL_DESCRIPTION_MAX / 2);
  });

  it('describes the variables the image actually reads, and cannot invent others', async () => {
    const { full } = await render(ENV_EXAMPLE);
    expect(full).toContain('MCP_AUTH_USER_KEY');
    expect(full).toContain('MCP_API_BASE_URL');
    // The failure this replaces: both live pages kept advertising a variable
    // retired two majors earlier, because the overview came from a README
    // snapshot instead of the server's own contract.
    expect(full).not.toContain('MCP_AUTH_PASSWORD');
    expect(full).not.toContain('MCP_AUTH_EMAIL');
  });

  it('separates required from optional so the required set is unmissable', async () => {
    const { full } = await render(ENV_EXAMPLE);
    const required = full.indexOf('Required');
    const optional = full.indexOf('Optional variables');
    expect(required).toBeGreaterThanOrEqual(0);
    expect(optional).toBeGreaterThan(required);
    expect(full.indexOf('MCP_AUTH_USER_KEY')).toBeLessThan(optional);
    // Match the TABLE ROW, not the bare name: the prose above mentions `PORT`
    // when explaining the HTTP transport, which is not a placement bug.
    expect(full.indexOf('| `PORT` |')).toBeGreaterThan(optional);
  });

  it('never leaks the annotation keys into the rendered table', async () => {
    const { full } = await render(ENV_EXAMPLE);
    expect(full).not.toContain('isRequired:');
    expect(full).not.toContain('isSecret:');
    expect(full).not.toContain('description:');
  });

  it('points its links at the product repo and the matching release tag', async () => {
    const { full } = await render(ENV_EXAMPLE);
    expect(full).toContain('https://github.com/g-digital-by-Garrigues/Test_MCP#readme');
    expect(full).toContain(
      'https://github.com/g-digital-by-Garrigues/Test_MCP/releases/tag/v2.0.0',
    );
  });

  it('returns the short description separately, for the one-liner under the repo name', async () => {
    const { short } = await render(ENV_EXAMPLE);
    expect(short).toBe('Test MCP server for certified evidence.');
  });
});

describe('readSourceRepoUrl', () => {
  it('resolves each product to its OWN repo, not the pipeline repo', async () => {
    for (const [name, expected] of [
      ['gocertius', 'https://github.com/g-digital-by-Garrigues/GoCertius_MCP'],
      ['ead-enterprise-suite', 'https://github.com/g-digital-by-Garrigues/EAD_Enterprise_Suite_MCP'],
    ] as const) {
      await expect(readSourceRepoUrl(repoRoot, name)).resolves.toBe(expected);
    }
  });

  it('throws rather than defaulting when the MCP is unknown', async () => {
    await expect(readSourceRepoUrl(repoRoot, 'no-such-mcp')).rejects.toThrow(/repo_url/);
  });
});
